INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('宁波诺丁汉大学', '金融助理研究员', '异地招聘', '9-13万/年', '10-08');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('巴罗克（上海）服饰有限公司', '招聘主管', '苏州', '7-9千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('盖茨优霓塔传动系统（苏州）有限公司', '资深电气技术员（倒三班）', '苏州-工业园区', '6-9千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('盖茨优霓塔传动系统（苏州）有限公司', '资深电气技术员（倒三班）', '苏州-工业园区', '6-9千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('江苏盘古管道科技有限公司', '电话客服+实习生+国外游', '苏州-吴中区', '6-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('可口可乐装瓶商生产（苏州）有限公司', '会计', '苏州', '6-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('江苏阿仕顿服饰有限公司', '空间设计（店铺）', '异地招聘', '6-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('上海契域投资管理有限公司', '金融销售/私募基金/6000+绩效奖金+提成+住宿（苏州）', '苏州-工业园区', '6-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('妙学巧记运营中心', '助教', '苏州-高新区', '6-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('上海大翊国际贸易有限公司', '分拣工（包吃住）', '苏州-相城区', '6-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州润弘非金属部件有限公司', '项目工程师', '苏州-吴江区', '6-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('昆山亿欧物业管理有限公司', '电工主管', '异地招聘', '6-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('上海契域投资管理有限公司', '金融销售/私募基金/6000+绩效奖金+提成+住宿（苏州）', '苏州-工业园区', '6-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('中外运-敦豪(DHL-Sinotrans)', '快递员-国际快件-苏州胜浦', '苏州', '6-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州联电能源发展有限公司', 'Web前端开发工程师', '苏州-工业园区', '5-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('无锡灵山文化旅游集团有限公司', '2019校园招聘管理储备', '异地招聘', '4.5-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('华尔街英语培训中心（上海）有限公司', 'Study Advisor学习顾问（英语老师/助教）-苏州', '苏州-姑苏区', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州朗阁外语培训中心', '市场专员（欧风）', '苏州', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('广州众跃跃贸易有限公司', '诚聘软件测试/经验不限', '异地招聘', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州金澄精密铸造有限公司', '仓库主管', '苏州', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('广州众跃跃贸易有限公司', '诚聘软件测试/经验不限', '异地招聘', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州驴拍文化传播有限公司', '行政司机', '苏州-高新区', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州晶储贸易有限公司', '客服（天猫/京东）', '苏州-工业园区', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州杨过餐饮管理有限公司', '食品厂操作工', '苏州-吴中区', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('渤海证券股份有限公司', '行政专员（党务方向）', '苏州', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州澜宭自动化科技有限公司', '业务助理', '苏州-工业园区', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('波噜噜儿童美语', '前台行政（汾湖校区）', '苏州-吴江区', '4.5-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州联电能源发展有限公司', 'UI界面设计师', '苏州-工业园区', '4.5-6.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州联电能源发展有限公司', 'UI界面设计师', '苏州-工业园区', '4.5-6.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州联电能源发展有限公司', 'UI界面设计师', '苏州-工业园区', '4.5-6.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州联电能源发展有限公司', 'UI界面设计师', '苏州-工业园区', '4.5-6.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('无锡市蜜桃餐饮管理有限公司', '蜜桃餐饮高薪诚聘管培生、储备干部', '苏州', '4.5-5千/月', '10-09');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州言知教育科技有限公司', '初高中化学老师', '苏州-相城区', '4-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州威特智能科技有限公司', '业务员挑战高薪+五险一金+包住+节日福利', '苏州-姑苏区', '4-8千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州欧尚超市有限公司', '欧尚金鸡湖店部门见习经理（实习）', '苏州', '4-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州欧尚超市有限公司', '欧尚金鸡湖店部门见习经理（实习）', '苏州', '4-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州翊曼生物科技有限公司', '销售行政助理（内勤）', '苏州', '4-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州欧尚超市有限公司', '欧尚金鸡湖店部门见习经理（实习）', '苏州', '4-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('淮安国际人语言培训中心', '小学英语老师', '异地招聘', '4-6千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州工业园区微笑口腔诊所有限公司', '口腔护士/护士长', '苏州-姑苏区', '3.5-5.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('鲁东东（苏州）餐饮管理有限公司', '前台', '苏州', '3.5-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('上海嘉扬信息系统有限公司', '行政财务助理（苏州分公司）', '苏州-高新区', '3-5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州博能炉窑科技有限公司', '机械设计', '苏州-工业园区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('美国美华少儿英语苏州培训中心', '人事行政专员（湖东）', '苏州-工业园区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('福禄（苏州）新型材料有限公司', '助理会计', '苏州-工业园区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('墨宝（苏州）知识产权股份有限公司', '会计', '苏州', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('福禄（苏州）新型材料有限公司', '助理会计', '苏州-工业园区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('墨宝（苏州）知识产权股份有限公司', '会计', '苏州', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('美国美华少儿英语苏州培训中心', '人事行政专员（湖东）', '苏州-工业园区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州格丽室新材料科技有限公司', '行政人事助理', '苏州-吴中区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('江苏小黄蜂智能科技有限公司', '人事行政助理', '苏州', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州丰品堂食品有限公司', '行政内勤', '苏州', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('卡博森斯化学科技（苏州）有限公司', '订单处理专员 （行政）', '苏州-工业园区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('重庆天骄爱生活服务股份有限公司苏...', '出纳兼行政', '苏州-工业园区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州元康健康管理咨询有限公司', '诚聘店助/储备店长晋升快待遇优', '苏州', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州云乐方文化传播有限公司', '行政文员/行政助理/人事/前台/总机', '苏州-工业园区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州子路企业服务有限公司', '行政实习生（双休+福利津贴）', '苏州-高新区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('福禄（苏州）新型材料有限公司', '助理会计', '苏州-工业园区', '3-4.5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州绿维新能源汽车有限公司', '平面设计师', '苏州-工业园区', '200元/小时', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州绿维新能源汽车有限公司', '平面设计师', '苏州-工业园区', '200元/小时', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州绿维新能源汽车有限公司', '平面设计师', '苏州-工业园区', '200元/小时', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州绿维新能源汽车有限公司', '平面设计师', '苏州-工业园区', '200元/小时', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('东南大学苏州医疗器械研究院', '细胞实验员', '苏州-高新区', '2-5千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州爱客汽车服务有限公司', '汽车美容学徒（擦车）', '苏州-工业园区', '2-4千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州爱客汽车服务有限公司', '汽车美容学徒（擦车）', '苏州-工业园区', '2-4千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州爱客汽车服务有限公司', '汽车美容学徒（擦车）', '苏州-工业园区', '2-4千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州爱客汽车服务有限公司', '汽车美容学徒（擦车）', '苏州-工业园区', '2-4千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州爱客汽车服务有限公司', '汽车美容学徒（擦车）', '苏州-工业园区', '2-4千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州爱客汽车服务有限公司', '汽车美容学徒（擦车）', '苏州-工业园区', '2-4千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('莱芬豪舍塑料机械（苏州）有限公司', '德资招市场推广员（在校大学生优先）', '苏州-吴江区', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('莱芬豪舍塑料机械（苏州）有限公司', '德资招市场推广员（在校大学生优先）', '苏州-吴江区', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州美集供应链管理股份有限公司', '出纳兼人事', '苏州', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州美集供应链管理股份有限公司', '出纳兼人事', '苏州', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州美集供应链管理股份有限公司', '出纳兼人事', '苏州', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州美集供应链管理股份有限公司', '出纳兼人事', '苏州', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州森歌建筑装饰工程有限公司', '施工员实习生', '苏州', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('江苏新合作常客隆连锁超市有限公司', '店员', '异地招聘', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州森歌建筑装饰工程有限公司', '施工员实习生', '苏州', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州旭屋建筑装饰工程有限公司', '办公室文员', '苏州', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('江苏新合作常客隆连锁超市有限公司', '店员', '异地招聘', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州欧尚超市有限公司', '商场美工人员', '苏州-工业园区', '2-3千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('江苏耐维思通科技股份有限公司', '高级电气工程师', '异地招聘', '2-2.5万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('江苏鸿恩医疗器械有限公司', '软件研发总监/经理', '异地招聘', '15-20万/年', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('United World College of Changsh...', 'Lab Assistant', '异地招聘', '100元/天', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('卡博森斯化学科技（苏州）有限公司', 'Part-time Job', '苏州-工业园区', '1.5-2千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('卡博森斯化学科技（苏州）有限公司', 'Part-time Job', '苏州-工业园区', '1.5-2千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('卡博森斯化学科技（苏州）有限公司', 'Part-time Job', '苏州-工业园区', '1.5-2千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('卡博森斯化学科技（苏州）有限公司', 'Part-time Job', '苏州-工业园区', '1.5-2千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('卡博森斯化学科技（苏州）有限公司', 'Part-time Job', '苏州-工业园区', '1.5-2千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('上海宝鄂实业有限公司', '销售底薪+提成无上限', '异地招聘', '1.5-2千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('卡博森斯化学科技（苏州）有限公司', 'Part-time Job', '苏州-工业园区', '1.5-2千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('卡博森斯化学科技（苏州）有限公司', 'Part-time Job', '苏州-工业园区', '1.5-2千/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('欧普照明股份有限公司', 'JAVA高级IT工程师-电商', '苏州-吴江区', '1.5-2万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('同程艺龙', 'QA测试工程师', '苏州', '1.5-2.5万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州阿特斯阳光电力科技有限公司', '事业部计划经理', '苏州', '1.5-2.5万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('同程艺龙', 'QA测试工程师', '苏州', '1.5-2.5万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州翔实医药发展有限公司', '博士--化学/有机化学--应届及有经验均可', '苏州', '1.4-4万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州思上环保科技有限公司', '环境工程主任设计师', '苏州-相城区', '1-2万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('同程艺龙', 'Java研发工程师', '苏州', '1-2.5万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('江苏万通教育集团', '首席执行官/总经理', '苏州', '1-1.5万/月', '09-25');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('卡博森斯化学科技（苏州）有限公司', '有机合成高级研究员', '苏州-工业园区', '1-1.5万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('雅马哈发动机（厦门）信息系统有限...', '办事处负责人', '苏州-工业园区', '1-1.5万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('北京云学堂网络科技有限公司', '运营助理', '苏州', '0.8-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('弘成科技发展有限公司', '招生办主任/校长-年终分红', '苏州', '0.8-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州黑白传媒有限公司', '资深平面设计师', '苏州-工业园区', '0.8-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('弘成科技发展有限公司', '招生办主任/校长-年终分红', '苏州', '0.8-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('深圳市小小金融服务有限公司', '金融实习生 底薪+提成+专业培训', '苏州-工业园区', '0.8-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('Tesla特斯拉汽车', 'Tesla 2019校园招聘-产品专员', '异地招聘', '0.8-1万/月', '09-24');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州臻旅网络科技有限公司', '高级web前端工程师', '苏州-工业园区', '0.8-1.6万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州臻旅网络科技有限公司', '高级web前端工程师', '苏州-工业园区', '0.8-1.6万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州臻旅网络科技有限公司', '高级web前端工程师', '苏州-工业园区', '0.8-1.6万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州臻旅网络科技有限公司', '高级web前端工程师', '苏州-工业园区', '0.8-1.6万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('上海NTT通信工程有限公司', '500强日企 SE部 系统集成工程师（服务器方向）', '苏州', '0.8-1.5万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('明基智能科技（上海）有限公司', 'JAVA开发工程师', '苏州', '0.6-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('明基智能科技（上海）有限公司', 'JAVA开发工程师', '苏州', '0.6-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('上海佐威实业有限公司', '苏州区域销售代表', '异地招聘', '0.6-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('中国人寿保险股份有限公司苏州市分...', '管理培训生-世界百强中国人寿', '苏州-吴中区', '0.6-1.5万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('北京航空航天大学苏州创新研究院', 'JAVA软件开发工程师', '苏州-高新区', '0.5-2万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('北京航空航天大学苏州创新研究院', 'JAVA软件开发工程师', '苏州-高新区', '0.5-2万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('北京航空航天大学苏州创新研究院', 'JAVA软件开发工程师', '苏州-高新区', '0.5-2万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('深圳市乐有家控股集团有限公司', '房地产营销储干', '苏州-吴中区', '0.5-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('深圳市乐有家控股集团有限公司', '房地产营销储干', '苏州-吴中区', '0.5-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('深圳市乐有家控股集团有限公司', '房地产营销储干', '苏州-吴中区', '0.5-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('深圳市乐有家控股集团有限公司', '房地产营销储干', '苏州-吴中区', '0.5-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('深圳市乐有家控股集团有限公司', '房地产营销储干', '苏州-吴中区', '0.5-1万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州工业园区西题迪斯教育培训中心', '课程销售代表（综合薪资5-15K）', '苏州-工业园区', '0.5-1.5万/月', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('瓦锡兰船用设备（苏州）有限公司', 'Operational Purchaser 采购工程师', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('瓦锡兰船用设备（苏州）有限公司', 'Operational Purchaser 采购工程师', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('西门子（中国）有限公司Siemens L...', '（SLC）人事专员（新区）（83830）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('西门子（中国）有限公司Siemens L...', '（SLC）人事专员（新区）（83830）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('西门子（中国）有限公司Siemens L...', '（SLC）人事专员（新区）（83830）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('西门子（中国）有限公司Siemens L...', '（SLC）人事专员（新区）（83830）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('西门子（中国）有限公司Siemens L...', '（SLC）人事专员（新区）（83830）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('西门子（中国）有限公司Siemens L...', '（SLC）人事专员（新区）（83830）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('西门子（中国）有限公司Siemens L...', '（SLC）人事专员（新区）（83830）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('思达耐精密机电(常熟)有限公司', '仓库管理员', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('瑞银企业管理（中国）有限公司', '瑞银集团（UBS）-运营部实习生', '异地招聘', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州西门子电器有限公司(SEAL)', '(SEAL)Technical Service Engineer 售后服务工程师 苏州（82410）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州西门子电器有限公司(SEAL)', '(SEAL)Technical Service Engineer 售后服务工程师 苏州（82410）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州西门子电器有限公司(SEAL)', '(SEAL)Technical Service Engineer 售后服务工程师 苏州（82410）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州西门子电器有限公司(SEAL)', '(SEAL)Technical Service Engineer 售后服务工程师 苏州（82410）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州西门子电器有限公司(SEAL)', '(SEAL)Technical Service Engineer 售后服务工程师 苏州（82410）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州西门子电器有限公司(SEAL)', '(SEAL)Technical Service Engineer 售后服务工程师 苏州（82410）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('', '', '', '', '');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('苏州西门子电器有限公司(SEAL)', '(SEAL)Technical Service Engineer 售后服务工程师 苏州（82410）', '苏州', '', '10-10');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('', '', '', '', '');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('', '', '', '', '');
INSERT INTO `job_search` (`company_name`, `job_name`, `working_city`, `salary`, `release_time`) VALUES ('', '', '', '', '');
